[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🚀 节点选择,https://raw.githubusercontent.com/llovely45/ACL4SSR/refs/heads/main/Clash/pubg.list
ruleset=🚀 节点选择,[]IP-CIDR,1.1.1.1/32,no-resolve
ruleset=🚀 节点选择,[]IP-CIDR,8.8.8.8/32,no-resolve

ruleset=🎯 全球直连,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/CFnat.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/juewuy/ShellClash/master/rules/ai.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Copilot.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/GithubCopilot.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Claude.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🎞 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎞 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎞 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=🇨🇳 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=🇨🇳 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🇨🇳 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🎞 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🎞 国外媒体,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Emby.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/proxy.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CMBlog.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/direct.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🍃 应用净化,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/IDM.list
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]☑️ 手动切换`[]📶 优选线路`[]🌏 亚太地区`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`🌍 欧洲地区`🌎 美洲地区`[]DIRECT`http://captive.apple.com/`300,,50
custom_proxy_group=☑️ 手动切换`select`[]REJECT`(?i)^(?!.*(warp|snip|cf|cdn|优选|worker)).*`http://captive.apple.com/`300,,50
custom_proxy_group=♻️ 自动选择`url-test`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`http://captive.apple.com/`300,,50
custom_proxy_group=📶 优选线路`url-test`[]REJECT`(?i)(防失联|warp|snip|cf|cdn|优选|worker)`http://captive.apple.com/`300,,50
custom_proxy_group=📲 电报消息`fallback`[]🌏 亚太地区`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🚀 节点选择`http://captive.apple.com/`300,,50
custom_proxy_group=🤖 OpenAi`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]📶 优选线路`[]☑️ 手动切换`[]DIRECT`http://captive.apple.com/`300,,50
custom_proxy_group=🎞 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🌏 亚太地区`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]📶 优选线路`[]☑️ 手动切换`[]DIRECT`http://captive.apple.com/`300,,50
custom_proxy_group=🇨🇳 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]☑️ 手动切换`http://captive.apple.com/`300,,50
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🌏 亚太地区`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]📶 优选线路`[]☑️ 手动切换`http://captive.apple.com/`300,,50
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🌏 亚太地区`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]📶 优选线路`[]☑️ 手动切换`http://captive.apple.com/`300,,50
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🌏 亚太地区`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]📶 优选线路`[]☑️ 手动切换`http://captive.apple.com/`300,,50
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🌏 亚太地区`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]📶 优选线路`[]☑️ 手动切换`http://captive.apple.com/`300,,50
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)`http://captive.apple.com/`300,,50
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`http://captive.apple.com/`300,,50
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT`http://captive.apple.com/`300,,50
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]📶 优选线路`[]☑️ 手动切换`http://captive.apple.com/`300,,50
custom_proxy_group=🇭🇰 香港节点`url-test`[]REJECT`(?i)(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)`http://captive.apple.com/`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`[]REJECT`(?i)(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|Tokyo|NRT|KIX)`http://captive.apple.com/`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`[]REJECT`(?i)(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)`http://captive.apple.com/`300,,150
custom_proxy_group=🇸🇬 狮城节点`url-test`[]REJECT`(?i)(新加坡|坡|狮城|SG|Singapore|SIN)`http://captive.apple.com/`300,,50
custom_proxy_group=🌏 亚太地区`url-test`[]REJECT`(?i)(港|HK|hk|Hong Kong|HongKong|hongkong|HKG|新加坡|坡|狮城|SG|Singapore|SIN|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|Tokyo|NRT|KIX)`http://captive.apple.com/`300,,50
custom_proxy_group=🌍 欧洲地区`url-test`[]REJECT`(?i)^(?!.*(港|HK|Hong Kong|HKG|新加坡|SG|Singapore|日本|JP|Japan|台湾|TW|Taiwan|韩国|KR|Korea|美国|US|United States|洛杉矶|纽约|Dallas|Chicago)).*(英国|UK|United Kingdom|伦敦|法国|FR|France|巴黎|德国|DE|Germany|法兰克福|荷兰|NL|Netherlands|阿姆斯特丹)`http://captive.apple.com/`300,,50
custom_proxy_group=🌎 美洲地区`url-test`[]REJECT`(?i)(美国|US|United States|洛杉矶|LAX|纽约|NYC|芝加哥|Chicago|达拉斯|Dallas|加拿大|CA|Canada|多伦多|Toronto|温哥华|Vancouver|巴西|BR|Brazil|圣保罗|Sao Paulo)`http://captive.apple.com/`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/llovely45/ACL4SSR/refs/heads/main/Clash/DNS-NoLeak.yml

;luck
